### ISSUE TITLE
Arabic translation not showing

### ISSUE THREAD

**Issue by HassanZahin** [naraesk/krunner-translator#15]
Just installed from deb package. But not showing translation.
![image](https://user-images.githubusercontent.com/61543143/93414489-3a617c80-f8c3-11ea-8069-f014a4bb6a09.png)

**Comment by naraesk** [comment]
Thanks for reporting. Guess that's a problem with non-ascii characters. I'll have a look at it.

**Comment by naraesk** [comment]
What do you use as primary and secondary language?

**Comment by HassanZahin** [comment]
On where? Keyboard layout or locales or language option in settings? Anyway, here are all the settings.
![image](https://user-images.githubusercontent.com/61543143/93437601-fc2d8280-f8ed-11ea-8cf5-891b6d86813c.png)
![image](https://user-images.githubusercontent.com/61543143/93437929-63e3cd80-f8ee-11ea-8d18-6e52b69d353d.png)
![image](https://user-images.githubusercontent.com/61543143/93437985-78c06100-f8ee-11ea-9ea0-4cb9632ed20b.png)

**Comment by HassanZahin** [comment]
Another thing confirmed. Hebrew also don't work. I think it's less related to language and more related to scripts that are written from right side.
![image](https://user-images.githubusercontent.com/61543143/93438274-e2406f80-f8ee-11ea-9dde-9c85eee2460a.png)

**Comment by naraesk** [comment]
The settings of this runner. Go to the settings of KRunner (using the icon on the left when KRunner is opened), then search for "Translator". There you can configure the used languages. Currently, the runner does not support automatic language detection, I guess that why it's not working. Please set the correct primary and secondary language, or specify both languages, e.g., `ar-en صباح الخير'. This displays "good morning" for me.

**Comment by HassanZahin** [comment]
Here it is:
![image](https://user-images.githubusercontent.com/61543143/93583800-32d6cc00-f9c6-11ea-85da-735714531e26.png)

**Comment by HassanZahin** [comment]
ar-en seems to also work for me.

**Comment by HassanZahin** [comment]
I think something is wrong. In google translate the only word is book. But translator is showing and.
![image](https://user-images.githubusercontent.com/61543143/93585748-12f4d780-f9c9-11ea-93da-f56f39e1cebe.png)

**Comment by naraesk** [comment]
There seems to some misunderstanding of how the runner is working. So let me explain. As you can see in the config dialog, English and Spanish are used as default languages. So "en صباح الخير" will translate "صباح الخير" from Spanish into English. In this case, Google Translate will also just show صباح الخير as translation:

![Screenshot_20200918_125946](https://user-images.githubusercontent.com/7393797/93590461-db793180-f9ae-11ea-8df2-6a4f817ff54c.png)

It is not possible to check if your input is a proper Spanish word. If you primarily translate from English into Arabish and vice versa, I'd recommend using Arabic instead of Spanish as the default language, then "en صباح الخير" will work. Otherwise, you have to use "ar-en صباح الخير". Currently, automatic language detection is not supported at the moment. But it will be added in the future. If you change settings, you have to restart krunner to take the new settings into account.

The correct abbreviation for welsh is cy. Using the long form is not supported, you also cannot use "arabic-english صباح الخير". Using the correct abbreviation it works just fine:
![Screenshot_20200918_130647](https://user-images.githubusercontent.com/7393797/93591010-d1a3fe00-f9af-11ea-9898-8b20a553574a.png)
